site_name: pixi-live2d-display

docs_dir: mkdocs

repo_url: https://github.com/guansss/pixi-live2d-display

nav:
  - Introduction: 'README.md'
  - References:
    - Models: 'models.md'
    - Interactions: 'interactions.md'
    - Motions and Expressions: 'motions_expressions.md'
    - Additional Features: 'additional.md'
    - Configs: 'configs.md'
    - Graphs: 'graphs.md'
  - Development: 'development.md'
  - API Documentation: 'api/index.html'

plugins:
  - search

theme:
  name: material
  features:
    - navigation.expand

markdown_extensions:
  - admonition
  - toc:
      permalink: True
  - pymdownx.highlight
  - sane_lists
  - def_list
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

google_analytics: ['G-KH8XQ1VPZW', 'guansss.github.io']
